#
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
#

Name:       %Name%

# >> macros
%{!?qtc_qmake:%define qtc_qmake qmake}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
# << macros

Summary:    %Summary%
Version:    %Version%
Release:    1
Group:      Qt/Qt
License:    LICENSE
Source0:    %{name}-%{version}.tar.bz2
Requires:   sailfishsilica
BuildRequires:  pkgconfig(QtCore) >= 4.8.0

%description
%Description%



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake

%qtc_make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post


%files
%defattr(-,root,root,-)

# >> files
# << files

