# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       %{ProjectName}

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    My Sailfish OS Plugin
Version:    0.1
Release:    1
Group:      Qt/Qt
License:    LICENSE
URL:        http://example.org/
Source0:    %{name}-%{version}.tar.bz2
Source100:  %{ProjectName}.yaml
Requires(post): /bin/touch

%description
Short description of my Sailfish OS Plugin


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%dir %{_libdir}/qt5/qml/%{PluginName}
%{_libdir}/qt5/qml/%{PluginName}/qmldir
%{_libdir}/qt5/qml/%{PluginName}/%{QmlPluginFileName}
%{_libdir}/qt5/qml/%{PluginName}/lib%{ProjectName}.so
/home/mersdk/share/projects/%{ProjectName}/plugin.qml
# >> files
# << files
